import { Outfit } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

// Import Outfit from Google Fonts
const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400","500","600", "700"], // You can adjust the weights as needed
  variable: "--font-outfit",
});

// Local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
